# User config
author: "OCrisp"
tagline: "Food clicks certified by Programmers"
description: "Because spaghetti and coders can be put in one sentence"
keywords: "Food photography, programmers, food, kitchen"
email: ""
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
plugins:
  - jemoji